#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 08 18:01:01 MSK 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sha256_top_tb_behav -key {Behavioral:sim_1:Functional:sha256_top_tb} -tclbatch sha256_top_tb.tcl -log simulate.log"
xsim sha256_top_tb_behav -key {Behavioral:sim_1:Functional:sha256_top_tb} -tclbatch sha256_top_tb.tcl -log simulate.log

